version: '3'

services:
  server:
    image: ryanprior/lutrine-dice-crystal:1.1.0-alpine
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      DIST_DIR: /opt/server/public
      LUTRINE_DB: sqlite3:/var/data/lutrine-dice.db
    volumes:
      - ./server:/opt/server
      - ./lutrine-dice.db:/var/data/lutrine-dice.db
      - ./client/dist:/opt/server/public
    working_dir: /opt/server
    command: crystal run src/main.cr -- --bind 0.0.0.0
    ports:
      - 3000:3000
  client:
    image: mintlang/mint
    volumes:
      - ./client:/opt/client
    working_dir: /opt/client
    command: start --host 0.0.0.0
    ports:
      - 3001:3000
