version: '3'

services:
  server:
    image: ryanprior/lutrine-dice-crystal:1.4-alpine
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      LUTRINE_ENV: local
      DIST_DIR: /opt/server/public
      LUTRINE_DB: sqlite3:/var/data/lutrine-dice.db
    volumes:
      - ./server:/opt/server
      - ./lutrine-dice.db:/var/data/lutrine-dice.db
      - ./client/dist:/opt/server/public
    working_dir: /opt/server
    command: crystal run src/main.cr -- --bind 0.0.0.0
    ports:
      - 3000:3000
  client:
    image: mintlang/mint
    volumes:
      - ./client:/opt/client
      - ./.env.dev:/var/data/env
    working_dir: /opt/client
    command: start --env /var/data/env --host 0.0.0.0
    ports:
      - 3001:3000
  client-behavior-test:
    image: quickstrom/quickstrom:0.5.0
    volumes:
      - ./client/specs:/specs
      - ./test-screenshots:/tmp
    # network_mode: host
    command: |
      quickstrom --log-level=DEBUG -I/specs
        check --capture-screenshots
        Rooms
        http://client:3000/
