FROM ryanprior/lutrine-dice-crystal:1.1.0-alpine AS build
WORKDIR /opt/server
COPY . ./
RUN shards build --release --static

FROM scratch
COPY --from=build /opt/server/bin/server ./server
ENTRYPOINT ["./server"]
